### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wouam31200** [comdif/FUSIONPBX-BILLING#1]
Hi,
Do you think it would be possible to add a button to return to FusionPBX?

For the installation, I did differently from you:

```
cd /usr/src
git clone https://github.com/comdif/FUSIONPBX-BILLING.git
cp -R /usr/src/FUSIONPBX-BILLING/mybilladmin /var/www/fusionpbx/app
chown -R www-data:www-data /var/www/fusionpbx/app/mybilladmin
```

Then in menu manager I added:

<img width="1515" alt="Capture d’écran 2024-06-04 à 12 27 06" src="https://github.com/comdif/FUSIONPBX-BILLING/assets/105128426/dc91f209-dd03-4521-98c2-0687bfc579ec">

Thank you so much!

**Comment by comdif** [comment]
Hello,
Yes sure just replace
`
	<li class="spe"><a href="index.php">MAIN</a></li>

	<li class="spe"><a href="new_rates.php">RATES</a></li>

	<li class="spe"><a href="importsql.php">RATES IMPORT</a></li>

	<li class="spe"><a href=""></a></li>

`
with

`	<li class="spe"><a href="index.php">MAIN</a></li>

	<li class="spe"><a href="new_rates.php">RATES</a></li>

	<li class="spe"><a href="importsql.php">RATES IMPORT</a></li>

	<li class="spe"><a href="https://'.$_SERVER['HTTP_HOST'].'">RETURN TO FUSIONPBX</a></li>

`
in the header.php file and voila
